# Generated by Django 5.2 on 2025-04-19 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_participant',
            field=models.BooleanField(default=False),
        ),
    ]
