# Generated by Django 5.2 on 2025-04-19 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_notification_request_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='phone',
        ),
    ]
