# Generated by Django 5.2 on 2025-04-19 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_member_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requete',
            name='status',
            field=models.CharField(choices=[('accepted', 'Accepted'), ('refused', 'Refused'), ('pending', 'Pending')], default='pending', max_length=10),
        ),
    ]
